### ISSUE TITLE
Cast to ObjectId failed

### ISSUE THREAD

**Issue by seanmavley** [Froelund/strapi-plugin-images#3]
When I do this

http://localhost:1337/images/052f24e0d2ee40d094d7c38a6d517aa7?size=100x100

I get this:

```
{ CastError: Cast to ObjectId failed for value "052f24e0d2ee40d094d7c38a6d517aa7" at path "_id" for model "UploadFile"
    at new CastError (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/error/cast.js:29:11)
    at ObjectId.cast (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/schema/objectid.js:232:11)
    at ObjectId.SchemaType.applySetters (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/schematype.js:845:12)
    at ObjectId.SchemaType._castForQuery (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/schematype.js:1248:15)
    at ObjectId.SchemaType.castForQuery (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/schematype.js:1238:15)
    at ObjectId.SchemaType.castForQueryWrapper (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/schematype.js:1217:15)
    at cast (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/cast.js:307:32)
    at model.Query.Query.cast (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/query.js:4262:12)
    at model.Query.Query._castConditions (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/query.js:1724:10)
    at model.Query.<anonymous> (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/query.js:1963:8)
    at model.Query._wrappedThunk [as _findOne] (/home/khophi/Developments/Strapi/Photog/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at /home/khophi/Developments/Strapi/Photog/node_modules/kareem/index.js:278:20
    at _next (/home/khophi/Developments/Strapi/Photog/node_modules/kareem/index.js:102:16)
    at process.nextTick (/home/khophi/Developments/Strapi/Photog/node_modules/kareem/index.js:499:38)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
  message:
   'Cast to ObjectId failed for value "052f24e0d2ee40d094d7c38a6d517aa7" at path "_id" for model "UploadFile"',
  name: 'CastError',
  stringValue: '"052f24e0d2ee40d094d7c38a6d517aa7"',
  kind: 'ObjectId',
  value: '052f24e0d2ee40d094d7c38a6d517aa7',
  path: '_id',
  reason: undefined,

```

**Comment by Froelund** [comment]
Hi Sean!
From the looks of it, it seems to be an issue with the supplied ObjectId.
